# development

[views]
cache = false

[static]
buffer = false
maxAge = 0

[passport]
providers = ["Facebook", "Google", "Twitter", "GitHub"]

[passport.strategies]

[passport.strategies.local]
# [module name, class]
Strategy = ["passport-local", "Strategy"]
[passport.strategies.local.options]
usernameField = "user[identifier]"
passwordField = "user[password]"
passReqToCallback = true

[passport.strategies.facebook]
protocol = "oauth2"
# [module name, class]
Strategy = ["passport-facebook", "Strategy"]
[passport.strategies.facebook.options]
scope = ["email", "public_profile"]
profileFields = ["id", "name", "displayName", "emails", "photos"]
clientID = "{{env.FACEBOOK_CLIENT_ID}}"
clientSecret = "{{env.FACEBOOK_CLIENT_SECRET}}"
callbackURL = "/auth/facebook/callback"
filter = "{{config.paths.get('lib')}}/lib/passport/facebook"

[passport.strategies.google]
protocol = "oauth2"
# [module name, class]
Strategy = ["passport-google-oauth", "OAuth2Strategy"]
[passport.strategies.google.options]
scope = ["email", "profile"]
clientID = "{{env.GOOGLE_CLIENT_ID}}"
clientSecret = "{{env.GOOGLE_CLIENT_SECRET}}"
callbackURL = "/auth/google/callback"
filter = "{{config.paths.get('lib')}}/passport/google"

[passport.strategies.twitter]
protocol = "oauth"
# [module name, class]
Strategy = ["passport-twitter", "Strategy"]
[passport.strategies.twitter.options]
clientID = "{{env.TWITTER_CONSUMER_KEY}}"
clientSecret = "{{env.TWITTER_CONSUMER_SECRET}}"
callbackURL = "/auth/twitter/callback"

[passport.strategies.github]
protocol = "oauth2"
# [module name, class]
Strategy = ["passport-github", "Strategy"]
[passport.strategies.github.options]
clientID = "{{env.GITHUB_CLIENT_ID}}"
clientSecret = "{{env.GITHUB_CLIENT_ID}}"
callbackURL = "/auth/github/callback"
